# Generated by Django 6.0.6 on 2026-06-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
